// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package store

import (
	"context"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (name, repo_url, health_path)
VALUES ($1, $2, $3)
RETURNING id, name, repo_url, health_path, created_at
`

type CreateAppParams struct {
	Name       string
	RepoUrl    string
	HealthPath string
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp, arg.Name, arg.RepoUrl, arg.HealthPath)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.HealthPath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM apps
WHERE name = $1
`

func (q *Queries) DeleteApp(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteApp, name)
	return err
}

const getAppByName = `-- name: GetAppByName :one
SELECT id, name, repo_url, health_path, created_at FROM apps
WHERE name = $1
`

func (q *Queries) GetAppByName(ctx context.Context, name string) (App, error) {
	row := q.db.QueryRow(ctx, getAppByName, name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.HealthPath,
		&i.CreatedAt,
	)
	return i, err
}

const listApps = `-- name: ListApps :many
SELECT id, name, repo_url, health_path, created_at FROM apps
ORDER BY created_at DESC
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.Query(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoUrl,
			&i.HealthPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
