// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_logs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeploymentLog = `-- name: CreateDeploymentLog :one
INSERT INTO deployment_logs (deployment_id, message)
VALUES ($1, $2)
RETURNING id, deployment_id, created_at, message
`

type CreateDeploymentLogParams struct {
	DeploymentID pgtype.UUID
	Message      string
}

func (q *Queries) CreateDeploymentLog(ctx context.Context, arg CreateDeploymentLogParams) (DeploymentLog, error) {
	row := q.db.QueryRow(ctx, createDeploymentLog, arg.DeploymentID, arg.Message)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.CreatedAt,
		&i.Message,
	)
	return i, err
}

const listDeploymentLogs = `-- name: ListDeploymentLogs :many
SELECT id, deployment_id, created_at, message FROM deployment_logs
WHERE deployment_id = $1
ORDER BY id ASC
`

func (q *Queries) ListDeploymentLogs(ctx context.Context, deploymentID pgtype.UUID) ([]DeploymentLog, error) {
	rows, err := q.db.Query(ctx, listDeploymentLogs, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentLog
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.CreatedAt,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentLogsAfter = `-- name: ListDeploymentLogsAfter :many
SELECT id, deployment_id, created_at, message FROM deployment_logs
WHERE deployment_id = $1
  AND id > $2
ORDER BY id ASC
`

type ListDeploymentLogsAfterParams struct {
	DeploymentID pgtype.UUID
	AfterID      int64
}

func (q *Queries) ListDeploymentLogsAfter(ctx context.Context, arg ListDeploymentLogsAfterParams) ([]DeploymentLog, error) {
	rows, err := q.db.Query(ctx, listDeploymentLogsAfter, arg.DeploymentID, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentLog
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.CreatedAt,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
