// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (app_id, image_tag)
VALUES ($1, $2)
RETURNING id, app_id, image_tag, status, container_id, internal_port, created_at, finished_at, error_message, rolled_back_from
`

type CreateDeploymentParams struct {
	AppID    pgtype.UUID
	ImageTag string
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment, arg.AppID, arg.ImageTag)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.InternalPort,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.RolledBackFrom,
	)
	return i, err
}

const getActiveDeploymentByApp = `-- name: GetActiveDeploymentByApp :one
SELECT id, app_id, image_tag, status, container_id, internal_port, created_at, finished_at, error_message, rolled_back_from FROM deployments
WHERE app_id = $1
  AND status = 'running'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveDeploymentByApp(ctx context.Context, appID pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getActiveDeploymentByApp, appID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.InternalPort,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.RolledBackFrom,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, app_id, image_tag, status, container_id, internal_port, created_at, finished_at, error_message, rolled_back_from FROM deployments
WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.InternalPort,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.RolledBackFrom,
	)
	return i, err
}

const listDeploymentsByApp = `-- name: ListDeploymentsByApp :many
SELECT id, app_id, image_tag, status, container_id, internal_port, created_at, finished_at, error_message, rolled_back_from FROM deployments
WHERE app_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByApp(ctx context.Context, appID pgtype.UUID) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ImageTag,
			&i.Status,
			&i.ContainerID,
			&i.InternalPort,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
			&i.RolledBackFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments
SET
    status        = $2,
    container_id  = COALESCE($3, container_id),
    internal_port = COALESCE($4, internal_port),
    finished_at   = COALESCE($5, finished_at),
    error_message = COALESCE($6, error_message)
WHERE id = $1
RETURNING id, app_id, image_tag, status, container_id, internal_port, created_at, finished_at, error_message, rolled_back_from
`

type UpdateDeploymentStatusParams struct {
	ID           pgtype.UUID
	Status       string
	ContainerID  pgtype.Text
	InternalPort pgtype.Int4
	FinishedAt   pgtype.Timestamptz
	ErrorMessage pgtype.Text
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeploymentStatus,
		arg.ID,
		arg.Status,
		arg.ContainerID,
		arg.InternalPort,
		arg.FinishedAt,
		arg.ErrorMessage,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageTag,
		&i.Status,
		&i.ContainerID,
		&i.InternalPort,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.RolledBackFrom,
	)
	return i, err
}
