// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID         pgtype.UUID
	Name       string
	RepoUrl    string
	HealthPath string
	CreatedAt  pgtype.Timestamptz
}

type Deployment struct {
	ID           pgtype.UUID
	AppID        pgtype.UUID
	ImageTag     string
	Status       string
	ContainerID  pgtype.Text
	InternalPort pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	ErrorMessage pgtype.Text
}
